# Generated by Django 5.1.2 on 2025-03-20 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('entries', models.IntegerField()),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=10)),
                ('fiat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crypto_currency', models.CharField(max_length=50)),
                ('fiat_currency', models.CharField(max_length=50)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('entries', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('fiat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crypto_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('fiat_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('initiated_crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('paid_crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('order_description', models.TextField(blank=True, null=True)),
                ('ipn_callback_url', models.URLField(blank=True, null=True)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('success_url', models.URLField(blank=True, null=True)),
                ('cancel_url', models.URLField(blank=True, null=True)),
                ('payin_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_address', models.CharField(blank=True, max_length=255, null=True)),
                ('payin_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('payout_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.package'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='home.userinfo'),
        ),
    ]
